### ISSUE TITLE
Form semantic incorrect

### ISSUE THREAD

**Issue by domjngo** [nationalarchives/tna-newsletter-wp-plugin#2]
**Describe the bug**
`<fieldset>` and `<legend>` outside `<form>`

eg:
```
<fieldset>
<legend>Legend</legend>
<form>
...
</form>
</fieldset>
```

**Expected behavior**
```
<form>
<fieldset>
<legend>Legend</legend>
...
</fieldset>
</form>
```

**Comment by punalsc** [comment]
The `<legend>` has a default styling property `border-bottom`  is coming from bootstrap, which needs an override.

The fix that @domingobishop has suggested should fix this.

**Comment by netdesignr** [comment]
Done
