### ISSUE TITLE
get_paragraph function

### ISSUE THREAD

**Issue by punalsc** [nationalarchives/tna-newsletter-wp-plugin#4]
Similar issue with the `get_paragraph()`

```php
public function get_paragraph() {
     if(function_exists('esc_attr')) {
          return !empty($this->content[1]) ? '<div class="form-row"><p>'. esc_attr($this->content[1]) .'</p></div>' : null;
     }
}
```

I would also suggest probably refactoring the code using `sprintf`, just to make the code look a bit neat. But this is optional.

https://www.php.net/manual/en/function.sprintf.php

**Comment by netdesignr** [comment]
Done!
