### ISSUE TITLE
Php errors in the form

### ISSUE THREAD

**Issue by punalsc** [nationalarchives/tna-newsletter-wp-plugin#5]
Hi @netdesignr

Getting some php errors.

To replicate this error, turn off JS in the browser to test for error messages.

![Screenshot 2019-08-27 at 18 33 44](https://user-images.githubusercontent.com/2183042/63794217-6b0df700-c8f9-11e9-9c17-170cd140007e.png)

**Comment by netdesignr** [comment]
As per instructions inside Readme  file please do the following:

On local development environment comment out the following lines in inc/api-connection.php
curl_setopt($curl, CURLOPT_PROXY, WP_PROXY_HOST . ':' . WP_PROXY_PORT);
curl_setopt($curl, CURLOPT_HTTPPROXYTUNNEL, 1);
